package com.familyvoice.reminders.ui.auth

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.familyvoice.reminders.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

private const val TAG = "AuthViewModel"

data class AuthUiState(
    val isAuthenticated: Boolean = false,
    val isLoading: Boolean       = false,
    val error: String?           = null,
)

@HiltViewModel
class AuthViewModel @Inject constructor(
    private val auth: FirebaseAuth,
) : ViewModel() {

    private val _state = MutableStateFlow(AuthUiState())
    val state: StateFlow<AuthUiState> = _state.asStateFlow()

    init {
        _state.update { it.copy(isAuthenticated = auth.currentUser != null) }
    }

    /**
     * Initiates Google Sign-In via Credential Manager and signs into Firebase.
     *
     * Runs inside [viewModelScope] — survives recompositions and system dialogs.
     * The [context] parameter (Activity context from LocalContext) is used only
     * during the call and is NOT stored in the ViewModel.
     *
     * [R.string.default_web_client_id] is auto-generated by the google-services plugin
     * from the OAuth 2.0 Web Client in google-services.json, or falls back to the
     * placeholder in strings.xml which the user must replace with their Firebase
     * Web Client ID.
     */
    fun signInWithGoogle(context: Context) {
        // Guard: ignore tap if already signing in
        if (_state.value.isLoading) return

        viewModelScope.launch {
            _state.update { it.copy(isLoading = true, error = null) }
            try {
                val webClientId = context.getString(R.string.default_web_client_id)
                Log.d(TAG, "Requesting credential with client: ${webClientId.take(30)}…")

                val credentialManager = CredentialManager.create(context)
                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(false)
                    .setServerClientId(webClientId)
                    .build()
                val request = GetCredentialRequest.Builder()
                    .addCredentialOption(googleIdOption)
                    .build()

                val result     = credentialManager.getCredential(context, request)
                val credential = result.credential

                if (credential is CustomCredential &&
                    credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                ) {
                    val idToken            = GoogleIdTokenCredential.createFrom(credential.data).idToken
                    val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                    auth.signInWithCredential(firebaseCredential).await()
                    Log.i(TAG, "Sign-in success: uid=${auth.currentUser?.uid}")
                    _state.update { it.copy(isAuthenticated = true, isLoading = false) }
                } else {
                    val msg = "Неподдерживаемый тип учётных данных: ${credential.type}"
                    Log.e(TAG, msg)
                    _state.update { it.copy(isLoading = false, error = msg) }
                }
            } catch (e: GetCredentialCancellationException) {
                Log.d(TAG, "Sign-in cancelled by user")
                _state.update { it.copy(isLoading = false, error = null) }
            } catch (e: GetCredentialException) {
                Log.e(TAG, "GetCredentialException", e)
                _state.update {
                    it.copy(isLoading = false, error = "Ошибка входа: ${e.localizedMessage ?: "Неизвестная ошибка"}")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Google sign-in failed", e)
                _state.update {
                    it.copy(isLoading = false, error = e.localizedMessage ?: "Неизвестная ошибка")
                }
            }
        }
    }

    fun signOut() {
        auth.signOut()
        _state.update { it.copy(isAuthenticated = false) }
    }
}
