package com.familyvoice.reminders.ui.auth

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.lifecycle.ViewModel
import com.familyvoice.reminders.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

private const val TAG = "AuthViewModel"

data class AuthUiState(
    val isAuthenticated: Boolean = false,
    val isLoading: Boolean       = true,
    val error: String?           = null,
)

@HiltViewModel
class AuthViewModel @Inject constructor(
    private val auth: FirebaseAuth,
) : ViewModel() {

    private val _state = MutableStateFlow(AuthUiState())
    val state: StateFlow<AuthUiState> = _state.asStateFlow()

    init {
        _state.update { it.copy(isAuthenticated = auth.currentUser != null, isLoading = false) }
    }

    /**
     * Launches Google Sign-In via Credential Manager and signs into Firebase.
     * Must be called from a coroutine that has access to an Activity [context]
     * (e.g. via [androidx.compose.ui.platform.LocalContext]).
     */
    /**
     * Initiates Google Sign-In via Credential Manager and signs into Firebase.
     * Must be called from a coroutine with an Activity/Compose context.
     *
     * [R.string.default_web_client_id] is either auto-generated by the google-services plugin
     * (Firebase Console → Auth → Google → Web Client ID) or defined manually in strings.xml.
     */
    suspend fun signInWithGoogle(context: Context) {
        _state.update { it.copy(isLoading = true, error = null) }
        try {
            val webClientId = context.getString(R.string.default_web_client_id)
            Log.d(TAG, "Using web client ID: ${webClientId.take(20)}…")

            val credentialManager = CredentialManager.create(context)
            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(webClientId)
                .build()
            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val result     = credentialManager.getCredential(context, request)
            val credential = result.credential

            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val idToken         = GoogleIdTokenCredential.createFrom(credential.data).idToken
                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                auth.signInWithCredential(firebaseCredential).await()
                Log.i(TAG, "Firebase sign-in success: uid=${auth.currentUser?.uid}")
                _state.update { it.copy(isAuthenticated = true, isLoading = false) }
            } else {
                val msg = "Неподдерживаемый тип учётных данных: ${credential.type}"
                Log.e(TAG, msg)
                _state.update { it.copy(isLoading = false, error = msg) }
            }
        } catch (e: GetCredentialCancellationException) {
            Log.d(TAG, "Sign-in cancelled by user")
            _state.update { it.copy(isLoading = false, error = null) }   // silent — user cancelled
        } catch (e: GetCredentialException) {
            Log.e(TAG, "GetCredentialException", e)
            _state.update { it.copy(isLoading = false, error = "Ошибка входа: ${e.localizedMessage ?: "Неизвестная ошибка"}") }
        } catch (e: Exception) {
            Log.e(TAG, "Google sign-in failed", e)
            _state.update { it.copy(isLoading = false, error = e.localizedMessage ?: "Неизвестная ошибка") }
        }
    }

    fun signOut() {
        auth.signOut()
        _state.update { it.copy(isAuthenticated = false) }
    }
}
